#!/usr/bin/env python3
"""Build self-contained NXP Cup learning pages from readable source assets."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
LEARN_ROOT = REPO_ROOT / "docs" / "learn"
SOURCE_ROOT = LEARN_ROOT / "src"
THREE_BUNDLE = LEARN_ROOT / "vendor" / "three" / "three.iife.min.js"
OUTPUT = LEARN_ROOT / "color-spaces.html"
RGB565_OUTPUT = LEARN_ROOT / "rgb565-lookup.html"

GENERATED_NOTICE = "<!-- Generated by scripts/tools/build_learning_pages.py. -->"
STYLE_MARKER = "<!-- __LESSON_CSS__ -->"
THREE_MARKER = "<!-- __THREE_JS__ -->"
APP_MARKER = "<!-- __LESSON_JS__ -->"


@dataclass(frozen=True)
class Lesson:
    slug: str
    output: Path
    include_three: bool = False


LESSONS = (
    Lesson("color-spaces", OUTPUT, include_three=True),
    Lesson("rgb565-lookup", RGB565_OUTPUT),
)


def _read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"required learning-page asset is missing: {path}")
    return path.read_text(encoding="utf-8")


def _safe_inline_script(path: Path) -> str:
    content = _read(path)
    if re.search(r"</script", content, flags=re.IGNORECASE):
        raise ValueError(f"inline script contains a closing script tag: {path}")
    return content


def render_lesson(lesson: Lesson) -> str:
    template = _read(SOURCE_ROOT / f"{lesson.slug}.template.html")
    css = _read(SOURCE_ROOT / "lesson.css")
    lesson_js = _safe_inline_script(SOURCE_ROOT / f"{lesson.slug}.js")

    markers = [STYLE_MARKER, APP_MARKER]
    if lesson.include_three:
        markers.append(THREE_MARKER)
    elif THREE_MARKER in template:
        raise ValueError(f"{lesson.slug} must not include unused Three.js payload")
    for marker in markers:
        if template.count(marker) != 1:
            raise ValueError(f"template must contain exactly one {marker}")

    rendered = template.replace(STYLE_MARKER, f"<style>\n{css}</style>")
    if lesson.include_three:
        three_js = _safe_inline_script(THREE_BUNDLE)
        rendered = rendered.replace(THREE_MARKER, f"<script>\n{three_js}</script>")
    rendered = rendered.replace(APP_MARKER, f"<script>\n{lesson_js}</script>")
    rendered = rendered.replace("<!-- __GENERATED_NOTICE__ -->", GENERATED_NOTICE)

    if "__LESSON_" in rendered or "__THREE_JS__" in rendered:
        raise ValueError("unresolved learning-page marker remains")
    if re.search(r"<(?:script|link)\b[^>]+(?:src|href)\s*=", rendered, re.IGNORECASE):
        raise ValueError("standalone learning page contains an external script or stylesheet")
    return rendered.replace("\r\n", "\n").rstrip() + "\n"


def render_color_spaces() -> str:
    return render_lesson(LESSONS[0])


def render_rgb565_lookup() -> str:
    return render_lesson(LESSONS[1])


def build(*, check: bool) -> int:
    status = 0
    for lesson in LESSONS:
        expected = render_lesson(lesson)
        current = (
            lesson.output.is_file()
            and lesson.output.read_text(encoding="utf-8") == expected
        )
        if check:
            if not current:
                print(f"stale or missing: {lesson.output}", file=sys.stderr)
                status = 1
            else:
                print(f"Standalone learning page is current: {lesson.output}")
        elif current:
            print(f"Standalone learning page already current: {lesson.output}")
        else:
            lesson.output.write_text(expected, encoding="utf-8", newline="\n")
            print(f"Built standalone learning page: {lesson.output}")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the committed output")
    arguments = parser.parse_args(argv)
    return build(check=arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
