#!/usr/bin/env python3
"""Generate the packed NXP Cup RGB565 to Y/H/S/V lookup table.

Every possible RGB565 value indexes one 32-bit entry:

    bits  7:0   Y, BT.601 luma
    bits 15:8   H, circular hue (256 bins span 0..<360 degrees)
    bits 23:16  S, HSV saturation
    bits 31:24  V, HSV value

The generated include file is deterministic and contains no timestamp or
machine-specific path. Use ``--check`` to verify committed output without
rewriting it.
"""

from __future__ import annotations

import argparse
import colorsys
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


RGB565_ENTRY_COUNT = 1 << 16
ENTRIES_PER_LINE = 8
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "src"
    / "embedded"
    / "nxp_cup_core0"
    / "source"
    / "nxpc_rgb565_yhsv_lut.inc"
)


@dataclass(frozen=True)
class ColorFeatures:
    """The four uint8 channels packed into a lookup-table entry."""

    y: int
    h: int
    s: int
    v: int

    @property
    def packed(self) -> int:
        return self.y | (self.h << 8) | (self.s << 16) | (self.v << 24)


def expand_rgb565(pixel: int) -> tuple[int, int, int]:
    """Expand RGB565 to RGB888 using bit replication."""
    if not 0 <= pixel < RGB565_ENTRY_COUNT:
        raise ValueError(f"RGB565 pixel is outside 0..65535: {pixel}")

    red_5 = (pixel >> 11) & 0x1F
    green_6 = (pixel >> 5) & 0x3F
    blue_5 = pixel & 0x1F
    return (
        (red_5 << 3) | (red_5 >> 2),
        (green_6 << 2) | (green_6 >> 4),
        (blue_5 << 3) | (blue_5 >> 2),
    )


def quantize_unit(value: float) -> int:
    """Quantize a clamped unit value using round-half-up semantics."""
    return min(255, max(0, int((value * 255.0) + 0.5)))


def color_features_for_rgb565(pixel: int) -> ColorFeatures:
    """Calculate Y/H/S/V for one RGB565 value."""
    red, green, blue = expand_rgb565(pixel)

    # BT.601 integer approximation. The +128 rounds instead of truncating.
    y = ((red * 77) + (green * 150) + (blue * 29) + 128) >> 8
    hue, saturation, value = colorsys.rgb_to_hsv(
        red / 255.0,
        green / 255.0,
        blue / 255.0,
    )

    # Hue is circular. Using 256 bins avoids representing zero and 360
    # degrees as two different byte values.
    hue_8 = int(hue * 256.0) & 0xFF
    return ColorFeatures(
        y=y,
        h=hue_8,
        s=quantize_unit(saturation),
        v=quantize_unit(value),
    )


def unpack_entry(packed: int) -> ColorFeatures:
    """Unpack one generated 32-bit Y/H/S/V entry."""
    if not 0 <= packed <= 0xFFFFFFFF:
        raise ValueError(f"packed entry is outside uint32: {packed}")
    return ColorFeatures(
        y=packed & 0xFF,
        h=(packed >> 8) & 0xFF,
        s=(packed >> 16) & 0xFF,
        v=(packed >> 24) & 0xFF,
    )


def validate_table(table: Sequence[int]) -> None:
    """Exhaustively validate indexing, packing, and luma accuracy."""
    if len(table) != RGB565_ENTRY_COUNT:
        raise ValueError(
            f"table has {len(table)} entries; expected {RGB565_ENTRY_COUNT}"
        )

    for pixel, packed in enumerate(table):
        actual = unpack_entry(packed)
        expected = color_features_for_rgb565(pixel)
        if actual != expected:
            raise ValueError(
                f"entry 0x{pixel:04X} is {actual}, expected {expected}"
            )

        red, green, blue = expand_rgb565(pixel)
        reference_y = quantize_unit(
            ((0.299 * red) + (0.587 * green) + (0.114 * blue)) / 255.0
        )
        if abs(actual.y - reference_y) > 1:
            raise ValueError(
                f"entry 0x{pixel:04X} luma {actual.y} differs from "
                f"BT.601 reference {reference_y} by more than one level"
            )


def generate_table() -> tuple[int, ...]:
    """Generate and validate all entries in RGB565 index order."""
    table = tuple(
        color_features_for_rgb565(pixel).packed
        for pixel in range(RGB565_ENTRY_COUNT)
    )
    validate_table(table)
    return table


def render_include(table: Sequence[int]) -> str:
    lines = [
        "/* Generated by scripts/tools/generate_rgb565_color_lut.py. Do not edit. */",
        "/* Entry layout, low to high byte: Y, H, S, V. */",
    ]
    for start in range(0, len(table), ENTRIES_PER_LINE):
        entries = table[start : start + ENTRIES_PER_LINE]
        lines.append("    " + " ".join(f"0x{entry:08X}u," for entry in entries))
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated include path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify existing output instead of writing it",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    content = render_include(generate_table())

    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != content:
            print(f"stale or missing: {args.output}", file=sys.stderr)
            return 1
        print(f"RGB565 YHSV LUT is current: {args.output}")
        return 0

    if args.output.is_file() and args.output.read_text(encoding="utf-8") == content:
        print(f"RGB565 YHSV LUT already current: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(f"generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
