
#ifndef AVC_CAMERA__MASTER_CONFIG_H_
#define AVC_CAMERA__MASTER_CONFIG_H_


#define CAMERA__OV7670							1
#define CAMERA__OV5640  						2
#define CAMERA__OV5460  						CAMERA__OV5640

//supported OV5640:
//FSL_VIDEO_RESOLUTION(320,200):
//FSL_VIDEO_RESOLUTION(320,102):
//FSL_VIDEO_RESOLUTION(160,120):
//FSL_VIDEO_RESOLUTION(320,240):

#define CONFIG__CAMERA_SELECT					(CAMERA__OV5640)

#define CAMERA_CAPTURE_BACKEND_SMARTDMA_EZH		1
#define CAMERA_CAPTURE_BACKEND_FLEXIO_DIAG		2
#define CAMERA_CAPTURE_BACKEND_FLEXIO_EDMA		3
#define CAMERA_CAPTURE_BACKEND_FLEXIO_PIPELINE_DIAG	4

#ifndef CONFIG__CAMERA_CAPTURE_BACKEND
#define CONFIG__CAMERA_CAPTURE_BACKEND			(CAMERA_CAPTURE_BACKEND_SMARTDMA_EZH)
#endif

#define CONFIG__CAMERA_RESOLUTION_X				(320)

#define CONFIG__CAMERA_RESOLUTION_Y				(200)

#define CONFIG__CAMERA_RESOLUTION				FSL_VIDEO_RESOLUTION(320, 200)

/*
 * Rev A competition baseline:
 * - camera capture through the original SmartDMA/EZH path
 * - original ER-TFT020-3 LCD over the existing SPI display path
 * - alternate ER-TFT020-7 TE and parallel bit-bang experiments disabled
 *
 * Both supported LCD panels use the same AVC LCD SPI pins in serial mode.
 * Change CONFIG__DISPLAY_PANEL to DISPLAY_PANEL_ER_TFT020_7 only for the
 * alternate BuyDisplay 2.0 inch 240x320 ST7789 panel.
 */
#define DISPLAY_PANEL_ER_TFT020_3				1
#define DISPLAY_PANEL_ER_TFT020_7				2

#ifndef CONFIG__DISPLAY_PANEL
#define CONFIG__DISPLAY_PANEL					(DISPLAY_PANEL_ER_TFT020_3)
#endif

#ifndef CONFIG__DISPLAY_TE_ENABLE
#define CONFIG__DISPLAY_TE_ENABLE				(0)
#endif

#ifndef CONFIG__DISPLAY_TEST_MODE
#define CONFIG__DISPLAY_TEST_MODE				(0)
#endif

#ifndef CONFIG__DISPLAY_PARALLEL_BITBANG_TEST_MODE
#define CONFIG__DISPLAY_PARALLEL_BITBANG_TEST_MODE	(0)
#endif

#ifndef CONFIG__DISPLAY_PARALLEL_BITBANG_WR_DELAY_CYCLES
#define CONFIG__DISPLAY_PARALLEL_BITBANG_WR_DELAY_CYCLES	(16U)
#endif

#ifndef CONFIG__DISPLAY_PARALLEL_BITBANG_FRAME_DELAY_MS
#define CONFIG__DISPLAY_PARALLEL_BITBANG_FRAME_DELAY_MS		(250U)
#endif

#if CONFIG__DISPLAY_PANEL != DISPLAY_PANEL_ER_TFT020_3 && CONFIG__DISPLAY_PANEL != DISPLAY_PANEL_ER_TFT020_7
#error Invalid CONFIG__DISPLAY_PANEL.
#endif

#if CONFIG__DISPLAY_TE_ENABLE && CONFIG__DISPLAY_PANEL != DISPLAY_PANEL_ER_TFT020_7
#error CONFIG__DISPLAY_TE_ENABLE is only valid for the alternate ER-TFT020-7 panel.
#endif

#if CONFIG__DISPLAY_PARALLEL_BITBANG_TEST_MODE && CONFIG__DISPLAY_PANEL != DISPLAY_PANEL_ER_TFT020_7
#error CONFIG__DISPLAY_PARALLEL_BITBANG_TEST_MODE is only valid for the alternate ER-TFT020-7 panel.
#endif

#ifndef CONFIG__USB_DEBUG_STREAM_ENABLE
#define CONFIG__USB_DEBUG_STREAM_ENABLE			(1)
#endif


//#define CONFIG__OV7670_IS_160x120 (1)           // This only applies to the OV7670

#if CONFIG__CAMERA_SELECT == CAMERA__OV7670

#if CONFIG__OV7670_IS_160x120 == 1
#define DEMO_BUFFER_WIDTH 120
#define DEMO_BUFFER_HEIGHT 160
#define DEMO_CAMERA_RESOLUTION kVIDEO_ResolutionQQVGA /* 160x120 */
#define DEMO_SMARTDMA_API kSMARTDMA_CameraWholeFrameQVGA
#else
#define DEMO_BUFFER_WIDTH 240
#define DEMO_BUFFER_HEIGHT 320
#define DEMO_CAMERA_RESOLUTION kVIDEO_ResolutionQVGA /* 320*240 */
#define DEMO_SMARTDMA_API kSMARTDMA_CameraWholeFrameQVGA
#endif

#elif CONFIG__CAMERA_SELECT == CAMERA__OV5640

#else

#error Invalid camera selection.

#endif

#endif
